### ISSUE TITLE
Fill in templates with team and project information

### ISSUE THREAD

**Issue by emilyperica** [emilyperica/ScoreGen#3]
Replace generic terms with team and project specific information in the following files:
- *\README.md
- docs\Common.tex
- ... anywhere else listing 'Project Name', 'Team Name', or similar.

**Comment by smiths** [comment]
I don't normally comment on student issues, but this one makes me happy.  :smile:  So many teams in the past have finished the term without filling in the team-specific information.  I actually added this requirement to the grading rubric.  The main README file in particular is important because that is the first thing that people see when they visit your page.
